
development:
  adapter: postgresql
  database: url_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: url_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: url
  pool: 5
  timeout: 5000